/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as OfficeIndexRouteImport } from './routes/office.index'
import { Route as ShopCheckoutRouteImport } from './routes/shop/checkout'
import { Route as ShopAccountRouteImport } from './routes/shop/account'
import { Route as OfficeTvRouteImport } from './routes/office.tv'
import { Route as OfficeSettingsRouteImport } from './routes/office.settings'
import { Route as OfficeSalesRepsRouteImport } from './routes/office.sales-reps'
import { Route as OfficeReportsRouteImport } from './routes/office.reports'
import { Route as OfficeReceivingRouteImport } from './routes/office.receiving'
import { Route as OfficePurchasingRouteImport } from './routes/office.purchasing'
import { Route as OfficeProductsRouteImport } from './routes/office.products'
import { Route as OfficePendingRouteImport } from './routes/office.pending'
import { Route as OfficePaymentsRouteImport } from './routes/office.payments'
import { Route as OfficeOrdersRouteImport } from './routes/office.orders'
import { Route as OfficeInvoicesRouteImport } from './routes/office.invoices'
import { Route as OfficeGpRouteImport } from './routes/office.gp'
import { Route as OfficeCustomersRouteImport } from './routes/office.customers'
import { Route as ShopOrdersIndexRouteImport } from './routes/shop/orders/index'
import { Route as ShopOrdersOrderNumberRouteImport } from './routes/shop/orders/$orderNumber'
import { Route as OfficeProductsNewRouteImport } from './routes/office.products.new'
import { Route as OfficeCustomersNewRouteImport } from './routes/office.customers.new'
import { Route as OfficeProductsIdEditRouteImport } from './routes/office.products.$id.edit'
import { Route as OfficeCustomersIdEditRouteImport } from './routes/office.customers.$id.edit'

const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const OfficeIndexRoute = OfficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficeRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRoute,
} as any)
const OfficeTvRoute = OfficeTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeSettingsRoute = OfficeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeSalesRepsRoute = OfficeSalesRepsRouteImport.update({
  id: '/sales-reps',
  path: '/sales-reps',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeReportsRoute = OfficeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeReceivingRoute = OfficeReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficePurchasingRoute = OfficePurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeProductsRoute = OfficeProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficePendingRoute = OfficePendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficePaymentsRoute = OfficePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeOrdersRoute = OfficeOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeInvoicesRoute = OfficeInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeGpRoute = OfficeGpRouteImport.update({
  id: '/gp',
  path: '/gp',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeCustomersRoute = OfficeCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => OfficeRoute,
} as any)
const ShopOrdersIndexRoute = ShopOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrdersOrderNumberRoute = ShopOrdersOrderNumberRouteImport.update({
  id: '/orders/$orderNumber',
  path: '/orders/$orderNumber',
  getParentRoute: () => ShopRoute,
} as any)
const OfficeProductsNewRoute = OfficeProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OfficeProductsRoute,
} as any)
const OfficeCustomersNewRoute = OfficeCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OfficeCustomersRoute,
} as any)
const OfficeProductsIdEditRoute = OfficeProductsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => OfficeProductsRoute,
} as any)
const OfficeCustomersIdEditRoute = OfficeCustomersIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => OfficeCustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/driver': typeof DriverRoute
  '/office': typeof OfficeRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/shop': typeof ShopRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/warehouse': typeof WarehouseRoute
  '/office/customers': typeof OfficeCustomersRouteWithChildren
  '/office/gp': typeof OfficeGpRoute
  '/office/invoices': typeof OfficeInvoicesRoute
  '/office/orders': typeof OfficeOrdersRoute
  '/office/payments': typeof OfficePaymentsRoute
  '/office/pending': typeof OfficePendingRoute
  '/office/products': typeof OfficeProductsRouteWithChildren
  '/office/purchasing': typeof OfficePurchasingRoute
  '/office/receiving': typeof OfficeReceivingRoute
  '/office/reports': typeof OfficeReportsRoute
  '/office/sales-reps': typeof OfficeSalesRepsRoute
  '/office/settings': typeof OfficeSettingsRoute
  '/office/tv': typeof OfficeTvRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/office/': typeof OfficeIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/office/customers/new': typeof OfficeCustomersNewRoute
  '/office/products/new': typeof OfficeProductsNewRoute
  '/shop/orders/$orderNumber': typeof ShopOrdersOrderNumberRoute
  '/shop/orders/': typeof ShopOrdersIndexRoute
  '/office/customers/$id/edit': typeof OfficeCustomersIdEditRoute
  '/office/products/$id/edit': typeof OfficeProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/driver': typeof DriverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/sign-in': typeof SignInRoute
  '/warehouse': typeof WarehouseRoute
  '/office/customers': typeof OfficeCustomersRouteWithChildren
  '/office/gp': typeof OfficeGpRoute
  '/office/invoices': typeof OfficeInvoicesRoute
  '/office/orders': typeof OfficeOrdersRoute
  '/office/payments': typeof OfficePaymentsRoute
  '/office/pending': typeof OfficePendingRoute
  '/office/products': typeof OfficeProductsRouteWithChildren
  '/office/purchasing': typeof OfficePurchasingRoute
  '/office/receiving': typeof OfficeReceivingRoute
  '/office/reports': typeof OfficeReportsRoute
  '/office/sales-reps': typeof OfficeSalesRepsRoute
  '/office/settings': typeof OfficeSettingsRoute
  '/office/tv': typeof OfficeTvRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/office': typeof OfficeIndexRoute
  '/shop': typeof ShopIndexRoute
  '/office/customers/new': typeof OfficeCustomersNewRoute
  '/office/products/new': typeof OfficeProductsNewRoute
  '/shop/orders/$orderNumber': typeof ShopOrdersOrderNumberRoute
  '/shop/orders': typeof ShopOrdersIndexRoute
  '/office/customers/$id/edit': typeof OfficeCustomersIdEditRoute
  '/office/products/$id/edit': typeof OfficeProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/driver': typeof DriverRoute
  '/office': typeof OfficeRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/shop': typeof ShopRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/warehouse': typeof WarehouseRoute
  '/office/customers': typeof OfficeCustomersRouteWithChildren
  '/office/gp': typeof OfficeGpRoute
  '/office/invoices': typeof OfficeInvoicesRoute
  '/office/orders': typeof OfficeOrdersRoute
  '/office/payments': typeof OfficePaymentsRoute
  '/office/pending': typeof OfficePendingRoute
  '/office/products': typeof OfficeProductsRouteWithChildren
  '/office/purchasing': typeof OfficePurchasingRoute
  '/office/receiving': typeof OfficeReceivingRoute
  '/office/reports': typeof OfficeReportsRoute
  '/office/sales-reps': typeof OfficeSalesRepsRoute
  '/office/settings': typeof OfficeSettingsRoute
  '/office/tv': typeof OfficeTvRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/office/': typeof OfficeIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/office/customers/new': typeof OfficeCustomersNewRoute
  '/office/products/new': typeof OfficeProductsNewRoute
  '/shop/orders/$orderNumber': typeof ShopOrdersOrderNumberRoute
  '/shop/orders/': typeof ShopOrdersIndexRoute
  '/office/customers/$id/edit': typeof OfficeCustomersIdEditRoute
  '/office/products/$id/edit': typeof OfficeProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/driver'
    | '/office'
    | '/reset-password'
    | '/sales'
    | '/shop'
    | '/sign-in'
    | '/warehouse'
    | '/office/customers'
    | '/office/gp'
    | '/office/invoices'
    | '/office/orders'
    | '/office/payments'
    | '/office/pending'
    | '/office/products'
    | '/office/purchasing'
    | '/office/receiving'
    | '/office/reports'
    | '/office/sales-reps'
    | '/office/settings'
    | '/office/tv'
    | '/shop/account'
    | '/shop/checkout'
    | '/office/'
    | '/shop/'
    | '/office/customers/new'
    | '/office/products/new'
    | '/shop/orders/$orderNumber'
    | '/shop/orders/'
    | '/office/customers/$id/edit'
    | '/office/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/driver'
    | '/reset-password'
    | '/sales'
    | '/sign-in'
    | '/warehouse'
    | '/office/customers'
    | '/office/gp'
    | '/office/invoices'
    | '/office/orders'
    | '/office/payments'
    | '/office/pending'
    | '/office/products'
    | '/office/purchasing'
    | '/office/receiving'
    | '/office/reports'
    | '/office/sales-reps'
    | '/office/settings'
    | '/office/tv'
    | '/shop/account'
    | '/shop/checkout'
    | '/office'
    | '/shop'
    | '/office/customers/new'
    | '/office/products/new'
    | '/shop/orders/$orderNumber'
    | '/shop/orders'
    | '/office/customers/$id/edit'
    | '/office/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/driver'
    | '/office'
    | '/reset-password'
    | '/sales'
    | '/shop'
    | '/sign-in'
    | '/warehouse'
    | '/office/customers'
    | '/office/gp'
    | '/office/invoices'
    | '/office/orders'
    | '/office/payments'
    | '/office/pending'
    | '/office/products'
    | '/office/purchasing'
    | '/office/receiving'
    | '/office/reports'
    | '/office/sales-reps'
    | '/office/settings'
    | '/office/tv'
    | '/shop/account'
    | '/shop/checkout'
    | '/office/'
    | '/shop/'
    | '/office/customers/new'
    | '/office/products/new'
    | '/shop/orders/$orderNumber'
    | '/shop/orders/'
    | '/office/customers/$id/edit'
    | '/office/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriverRoute: typeof DriverRoute
  OfficeRoute: typeof OfficeRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalesRoute: typeof SalesRoute
  ShopRoute: typeof ShopRouteWithChildren
  SignInRoute: typeof SignInRoute
  WarehouseRoute: typeof WarehouseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/office/': {
      id: '/office/'
      path: '/'
      fullPath: '/office/'
      preLoaderRoute: typeof OfficeIndexRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/account': {
      id: '/shop/account'
      path: '/account'
      fullPath: '/shop/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRoute
    }
    '/office/tv': {
      id: '/office/tv'
      path: '/tv'
      fullPath: '/office/tv'
      preLoaderRoute: typeof OfficeTvRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/settings': {
      id: '/office/settings'
      path: '/settings'
      fullPath: '/office/settings'
      preLoaderRoute: typeof OfficeSettingsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/sales-reps': {
      id: '/office/sales-reps'
      path: '/sales-reps'
      fullPath: '/office/sales-reps'
      preLoaderRoute: typeof OfficeSalesRepsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/reports': {
      id: '/office/reports'
      path: '/reports'
      fullPath: '/office/reports'
      preLoaderRoute: typeof OfficeReportsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/receiving': {
      id: '/office/receiving'
      path: '/receiving'
      fullPath: '/office/receiving'
      preLoaderRoute: typeof OfficeReceivingRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/purchasing': {
      id: '/office/purchasing'
      path: '/purchasing'
      fullPath: '/office/purchasing'
      preLoaderRoute: typeof OfficePurchasingRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/products': {
      id: '/office/products'
      path: '/products'
      fullPath: '/office/products'
      preLoaderRoute: typeof OfficeProductsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/pending': {
      id: '/office/pending'
      path: '/pending'
      fullPath: '/office/pending'
      preLoaderRoute: typeof OfficePendingRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/payments': {
      id: '/office/payments'
      path: '/payments'
      fullPath: '/office/payments'
      preLoaderRoute: typeof OfficePaymentsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/orders': {
      id: '/office/orders'
      path: '/orders'
      fullPath: '/office/orders'
      preLoaderRoute: typeof OfficeOrdersRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/invoices': {
      id: '/office/invoices'
      path: '/invoices'
      fullPath: '/office/invoices'
      preLoaderRoute: typeof OfficeInvoicesRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/gp': {
      id: '/office/gp'
      path: '/gp'
      fullPath: '/office/gp'
      preLoaderRoute: typeof OfficeGpRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/customers': {
      id: '/office/customers'
      path: '/customers'
      fullPath: '/office/customers'
      preLoaderRoute: typeof OfficeCustomersRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/shop/orders/': {
      id: '/shop/orders/'
      path: '/orders'
      fullPath: '/shop/orders/'
      preLoaderRoute: typeof ShopOrdersIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/orders/$orderNumber': {
      id: '/shop/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/shop/orders/$orderNumber'
      preLoaderRoute: typeof ShopOrdersOrderNumberRouteImport
      parentRoute: typeof ShopRoute
    }
    '/office/products/new': {
      id: '/office/products/new'
      path: '/new'
      fullPath: '/office/products/new'
      preLoaderRoute: typeof OfficeProductsNewRouteImport
      parentRoute: typeof OfficeProductsRoute
    }
    '/office/customers/new': {
      id: '/office/customers/new'
      path: '/new'
      fullPath: '/office/customers/new'
      preLoaderRoute: typeof OfficeCustomersNewRouteImport
      parentRoute: typeof OfficeCustomersRoute
    }
    '/office/products/$id/edit': {
      id: '/office/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/office/products/$id/edit'
      preLoaderRoute: typeof OfficeProductsIdEditRouteImport
      parentRoute: typeof OfficeProductsRoute
    }
    '/office/customers/$id/edit': {
      id: '/office/customers/$id/edit'
      path: '/$id/edit'
      fullPath: '/office/customers/$id/edit'
      preLoaderRoute: typeof OfficeCustomersIdEditRouteImport
      parentRoute: typeof OfficeCustomersRoute
    }
  }
}

interface OfficeCustomersRouteChildren {
  OfficeCustomersNewRoute: typeof OfficeCustomersNewRoute
  OfficeCustomersIdEditRoute: typeof OfficeCustomersIdEditRoute
}

const OfficeCustomersRouteChildren: OfficeCustomersRouteChildren = {
  OfficeCustomersNewRoute: OfficeCustomersNewRoute,
  OfficeCustomersIdEditRoute: OfficeCustomersIdEditRoute,
}

const OfficeCustomersRouteWithChildren = OfficeCustomersRoute._addFileChildren(
  OfficeCustomersRouteChildren,
)

interface OfficeProductsRouteChildren {
  OfficeProductsNewRoute: typeof OfficeProductsNewRoute
  OfficeProductsIdEditRoute: typeof OfficeProductsIdEditRoute
}

const OfficeProductsRouteChildren: OfficeProductsRouteChildren = {
  OfficeProductsNewRoute: OfficeProductsNewRoute,
  OfficeProductsIdEditRoute: OfficeProductsIdEditRoute,
}

const OfficeProductsRouteWithChildren = OfficeProductsRoute._addFileChildren(
  OfficeProductsRouteChildren,
)

interface OfficeRouteChildren {
  OfficeCustomersRoute: typeof OfficeCustomersRouteWithChildren
  OfficeGpRoute: typeof OfficeGpRoute
  OfficeInvoicesRoute: typeof OfficeInvoicesRoute
  OfficeOrdersRoute: typeof OfficeOrdersRoute
  OfficePaymentsRoute: typeof OfficePaymentsRoute
  OfficePendingRoute: typeof OfficePendingRoute
  OfficeProductsRoute: typeof OfficeProductsRouteWithChildren
  OfficePurchasingRoute: typeof OfficePurchasingRoute
  OfficeReceivingRoute: typeof OfficeReceivingRoute
  OfficeReportsRoute: typeof OfficeReportsRoute
  OfficeSalesRepsRoute: typeof OfficeSalesRepsRoute
  OfficeSettingsRoute: typeof OfficeSettingsRoute
  OfficeTvRoute: typeof OfficeTvRoute
  OfficeIndexRoute: typeof OfficeIndexRoute
}

const OfficeRouteChildren: OfficeRouteChildren = {
  OfficeCustomersRoute: OfficeCustomersRouteWithChildren,
  OfficeGpRoute: OfficeGpRoute,
  OfficeInvoicesRoute: OfficeInvoicesRoute,
  OfficeOrdersRoute: OfficeOrdersRoute,
  OfficePaymentsRoute: OfficePaymentsRoute,
  OfficePendingRoute: OfficePendingRoute,
  OfficeProductsRoute: OfficeProductsRouteWithChildren,
  OfficePurchasingRoute: OfficePurchasingRoute,
  OfficeReceivingRoute: OfficeReceivingRoute,
  OfficeReportsRoute: OfficeReportsRoute,
  OfficeSalesRepsRoute: OfficeSalesRepsRoute,
  OfficeSettingsRoute: OfficeSettingsRoute,
  OfficeTvRoute: OfficeTvRoute,
  OfficeIndexRoute: OfficeIndexRoute,
}

const OfficeRouteWithChildren =
  OfficeRoute._addFileChildren(OfficeRouteChildren)

interface ShopRouteChildren {
  ShopAccountRoute: typeof ShopAccountRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopOrdersOrderNumberRoute: typeof ShopOrdersOrderNumberRoute
  ShopOrdersIndexRoute: typeof ShopOrdersIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAccountRoute: ShopAccountRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopOrdersOrderNumberRoute: ShopOrdersOrderNumberRoute,
  ShopOrdersIndexRoute: ShopOrdersIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriverRoute: DriverRoute,
  OfficeRoute: OfficeRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SalesRoute: SalesRoute,
  ShopRoute: ShopRouteWithChildren,
  SignInRoute: SignInRoute,
  WarehouseRoute: WarehouseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
