/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopCheckoutRouteImport } from './routes/shop/checkout'
import { Route as ShopAccountRouteImport } from './routes/shop/account'
import { Route as ShopOrdersIndexRouteImport } from './routes/shop/orders/index'
import { Route as ShopOrdersOrderNumberRouteImport } from './routes/shop/orders/$orderNumber'

const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrdersIndexRoute = ShopOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrdersOrderNumberRoute = ShopOrdersOrderNumberRouteImport.update({
  id: '/orders/$orderNumber',
  path: '/orders/$orderNumber',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/driver': typeof DriverRoute
  '/office': typeof OfficeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/shop': typeof ShopRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/warehouse': typeof WarehouseRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/orders/$orderNumber': typeof ShopOrdersOrderNumberRoute
  '/shop/orders/': typeof ShopOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/driver': typeof DriverRoute
  '/office': typeof OfficeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/sign-in': typeof SignInRoute
  '/warehouse': typeof WarehouseRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop': typeof ShopIndexRoute
  '/shop/orders/$orderNumber': typeof ShopOrdersOrderNumberRoute
  '/shop/orders': typeof ShopOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/driver': typeof DriverRoute
  '/office': typeof OfficeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/shop': typeof ShopRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/warehouse': typeof WarehouseRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/orders/$orderNumber': typeof ShopOrdersOrderNumberRoute
  '/shop/orders/': typeof ShopOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/driver'
    | '/office'
    | '/reset-password'
    | '/sales'
    | '/shop'
    | '/sign-in'
    | '/warehouse'
    | '/shop/account'
    | '/shop/checkout'
    | '/shop/'
    | '/shop/orders/$orderNumber'
    | '/shop/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/driver'
    | '/office'
    | '/reset-password'
    | '/sales'
    | '/sign-in'
    | '/warehouse'
    | '/shop/account'
    | '/shop/checkout'
    | '/shop'
    | '/shop/orders/$orderNumber'
    | '/shop/orders'
  id:
    | '__root__'
    | '/'
    | '/driver'
    | '/office'
    | '/reset-password'
    | '/sales'
    | '/shop'
    | '/sign-in'
    | '/warehouse'
    | '/shop/account'
    | '/shop/checkout'
    | '/shop/'
    | '/shop/orders/$orderNumber'
    | '/shop/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriverRoute: typeof DriverRoute
  OfficeRoute: typeof OfficeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalesRoute: typeof SalesRoute
  ShopRoute: typeof ShopRouteWithChildren
  SignInRoute: typeof SignInRoute
  WarehouseRoute: typeof WarehouseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/account': {
      id: '/shop/account'
      path: '/account'
      fullPath: '/shop/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/orders/': {
      id: '/shop/orders/'
      path: '/orders'
      fullPath: '/shop/orders/'
      preLoaderRoute: typeof ShopOrdersIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/orders/$orderNumber': {
      id: '/shop/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/shop/orders/$orderNumber'
      preLoaderRoute: typeof ShopOrdersOrderNumberRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopAccountRoute: typeof ShopAccountRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopOrdersOrderNumberRoute: typeof ShopOrdersOrderNumberRoute
  ShopOrdersIndexRoute: typeof ShopOrdersIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAccountRoute: ShopAccountRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopOrdersOrderNumberRoute: ShopOrdersOrderNumberRoute,
  ShopOrdersIndexRoute: ShopOrdersIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriverRoute: DriverRoute,
  OfficeRoute: OfficeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalesRoute: SalesRoute,
  ShopRoute: ShopRouteWithChildren,
  SignInRoute: SignInRoute,
  WarehouseRoute: WarehouseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
